# Generated by Django 6.0.6 on 2026-07-15 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_persontovisit_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='person_to_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to='visitors.persontovisit'),
        ),
    ]
