# Generated by Django 6.0.6 on 2026-07-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitlog_person_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='person_to_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to='visitors.persontovisit'),
        ),
    ]
