# Generated by Django 6.0.6 on 2026-07-15 05:19

import visitors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_alter_visitlog_person_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='check_in_time',
            field=models.TimeField(default=visitors.models.current_time),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='visit_date',
            field=models.DateField(default=visitors.models.current_date),
        ),
    ]
