# Generated by Django 6.0.6 on 2026-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_alter_visitlog_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
